#pragma once
// Recipe File App Name
#define STACKEROCR_APPNAME		_T("STACKER_TRAY_OCR")
#define TRAYOCR_APPNAME			_T("TRAY_OCR")
#define TOPCHIPCNT_APPNAME		_T("3D_CHIP_CNT")
#define CHIPOCR_APPNAME			_T("CHIP_OCR")
#define CHIP_APPNAME			_T("CHIP_INFO")
#define MIXING_APPNAME			_T("MIXING")
#define LIFT_APPNAME			_T("LIFT_INFO")
#define BANDING_APPNAME			_T("BANDING_INFO")
#define HIC_APPNAME				_T("HIC_INFO")
#define DESICCANT_APPNAME		_T("DESICCANT_INFO")
#define SUBMATERIAL_APPNAME		_T("SUBMATERIAL_INFO")
#define	SUBMATERIALTRAY_APPNAME	_T("SUBMATERIALTRAY_INFO")
#define MBB_APPNAME				_T("MBB_INFO")
#define LABEL_APPNAME			_T("LABEL_INFO")
#define BOXQUALITY_APPNAME		_T("BOX_QUALITY_INFO")
#define SEALINGQUALITY_APPNAME	_T("SEALING_QUALITY_INFO")
#define BOXTAPE_APPNAME			_T("BOXTAPE_INFO")

// Recipe Kind
#define STACKEROCR_KIND			_T("SG_StackerOcr")
#define TRAYOCR_KIND			_T("1G_TrayOcr")
#define TOPCHIPCNT_KIND			_T("1G_3DChipCnt")
#define CHIPOCR_KIND			_T("1G_ChipOcr")
#define CHIP_KIND				_T("1G_Chip")
#define MIXING_KIND				_T("1G_Mixing")
#define LIFT_KIND				_T("1G_Lift")
#define BANDING_KIND			_T("2G_Banding")
#define HIC_KIND				_T("2G_HIC")
#define DESICCANT_KIND			_T("3G_Desiccant_Cutting")
#define SUBMATERIAL_KIND		_T("3G_Desiccant_Material")
#define SUBMATERIALTRAY_KIND	_T("3G_Desiccant_Material_Tray")
#define MBB_KIND				_T("4G_MBB")
#define BOXQUALITY_KIND			_T("5G_Box")
#define SEALINGQUALITY_KIND		_T("5G_Sealing")
#define BOXTAPE_KIND			_T("6G_Tape")
#define LABEL_KIND				_T("Label")